import { Article } from './Article';

export const Articles: Article[] = [
  {
    ID: 1,
    Image: './assets/img/photo-1.jpeg',
    Title: 'West Dorothy',
    Tag: 'Wild',
    Description: 'Time is best, until you own it',
    Vistor: 75,
    Date: '29-Nov-2018',
    Detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    comment:[
      {userid:1,comment_user:'Mohr',comment:'hello world',time:'5 days ago'},
      {userid:2,comment_user:'Strosin',comment:'hi there!',time:'Yesterday at 12:30AM'},
      {userid:3,comment_user:'Dandre',comment:'that is comment reply',time:'Today at 5:42PM'},
      {userid:4,comment_user:'Mayer',comment:'This has been very useful for my research. Thanks as well!',time:'5 minutes ago'},
    ],
  },
  {
    ID: 2,
    Image: './assets/img/photo-2.jpeg',
    Title: 'Marianeborough',
    Tag: 'Sky',
    Description: 'Theres magic in everyday',
    Vistor: 32,
    Date: '23-Oct-2018',
    Detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    comment:[
      {userid:1,comment_user:'Mohr',comment:'hello world',time:'5 days ago'},
      {userid:2,comment_user:'Strosin',comment:'hi there!',time:'Yesterday at 12:30AM'},
      {userid:3,comment_user:'Dandre',comment:'that is comment reply',time:'Today at 5:42PM'},
      {userid:4,comment_user:'Mayer',comment:'This has been very useful for my research. Thanks as well!',time:'5 minutes ago'},
    ],
  },
  {
    ID: 3,
    Image: './assets/img/photo-3.jpeg',
    Title: 'Kunzehaven',
    Tag: 'Sunny',
    Description: 'Mountains are always best, they stand firm and dont change',
    Vistor: 46,
    Date: '1-Sep-2018',
    Detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    comment:[
      {userid:1,comment_user:'Mohr',comment:'hello world',time:'5 days ago'},
      {userid:2,comment_user:'Strosin',comment:'hi there!',time:'Yesterday at 12:30AM'},
      {userid:3,comment_user:'Dandre',comment:'that is comment reply',time:'Today at 5:42PM'},
      {userid:4,comment_user:'Mayer',comment:'This has been very useful for my research. Thanks as well!',time:'5 minutes ago'},
    ],
  },
  {
    ID: 4,
    Image: './assets/img/photo-4.jpeg',
    Title: 'Mitchellfort',
    Tag: 'Ocean',
    Description: 'Job fills pockets, Adventure fills soul..',
    Vistor: 70,
    Date: '9-Otc-2018',
    Detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    comment:[
      {userid:1,comment_user:'Mohr',comment:'hello world',time:'5 days ago'},
      {userid:2,comment_user:'Strosin',comment:'hi there!',time:'Yesterday at 12:30AM'},
      {userid:3,comment_user:'Dandre',comment:'that is comment reply',time:'Today at 5:42PM'},
      {userid:4,comment_user:'Mayer',comment:'This has been very useful for my research. Thanks as well!',time:'5 minutes ago'},
    ],
  },
  {
    ID: 5,
    Image: './assets/img/photo-5.jpeg',
    Title: 'Arvidside',
    Tag: 'City',
    Description: 'Everyone wants to achieve sky',
    Vistor: 67,
    Date: '11-Sep-2018',
    Detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    comment:[
      {userid:1,comment_user:'Mohr',comment:'hello world',time:'5 days ago'},
      {userid:2,comment_user:'Strosin',comment:'hi there!',time:'Yesterday at 12:30AM'},
      {userid:3,comment_user:'Dandre',comment:'that is comment reply',time:'Today at 5:42PM'},
      {userid:4,comment_user:'Mayer',comment:'This has been very useful for my research. Thanks as well!',time:'5 minutes ago'},
    ],
  },
  {
    ID: 6,
    Image: './assets/img/photo-6.jpeg',
    Title: 'Arvidside',
    Tag: 'Flower',
    Description: 'Flowers and beauty all lies together',
    Vistor: 21,
    Date: '3-Sep-2018',
    Detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    comment:[
      {userid:1,comment_user:'Mohr',comment:'hello world',time:'5 days ago'},
      {userid:2,comment_user:'Strosin',comment:'hi there!',time:'Yesterday at 12:30AM'},
      {userid:3,comment_user:'Dandre',comment:'that is comment reply',time:'Today at 5:42PM'},
      {userid:4,comment_user:'Mayer',comment:'This has been very useful for my research. Thanks as well!',time:'5 minutes ago'},
    ],
  },
  {
    ID: 7,
    Image: './assets/img/photo-7.jpeg',
    Title: 'South Donnietown',
    Tag: 'Building',
    Description: 'Arcitectures are the ones crafting tommarow',
    Vistor: 42,
    Date: '5-Jun-2018',
    Detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    comment:[
      {userid:1,comment_user:'Mohr',comment:'hello world',time:'5 days ago'},
      {userid:2,comment_user:'Strosin',comment:'hi there!',time:'Yesterday at 12:30AM'},
      {userid:3,comment_user:'Dandre',comment:'that is comment reply',time:'Today at 5:42PM'},
      {userid:4,comment_user:'Mayer',comment:'This has been very useful for my research. Thanks as well!',time:'5 minutes ago'},
    ],
  },
  {
    ID: 8,
    Image: './assets/img/photo-8.jpeg',
    Title: 'Hagenesside',
    Tag: 'Motain',
    Description: 'Mountains are way standing firm',
    Vistor: 33,
    Date: '1-Jun-2018',
    Detail:'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    comment:[
      {userid:1,comment_user:'Mohr',comment:'hello world',time:'5 days ago'},
      {userid:2,comment_user:'Strosin',comment:'hi there!',time:'Yesterday at 12:30AM'},
      {userid:3,comment_user:'Dandre',comment:'that is comment reply',time:'Today at 5:42PM'},
      {userid:4,comment_user:'Mayer',comment:'This has been very useful for my research. Thanks as well!',time:'5 minutes ago'},
    ],
  }
];